// Mega Stone Forme Changes
const MEGA_STONES = {
  'Abomasnow': [{ item: 'Abomasite', forme: 'Abomasnow-Mega' }],
  'Absol': [{ item: 'Absolite', forme: 'Absol-Mega' }],
  'Aerodactyl': [{ item: 'Aerodactylite', forme: 'Aerodactyl-Mega' }],
  'Aggron': [{ item: 'Aggronite', forme: 'Aggron-Mega' }],
  'Alakazam': [{ item: 'Alakazite', forme: 'Alakazam-Mega' }],
  'Altaria': [{ item: 'Altarianite', forme: 'Altaria-Mega' }],
  'Ampharos': [{ item: 'Ampharosite', forme: 'Ampharos-Mega' }],
  'Audino': [{ item: 'Audinite', forme: 'Audino-Mega' }],
  'Banette': [{ item: 'Banettite', forme: 'Banette-Mega' }],
  'Beedrill': [{ item: 'Beedrillite', forme: 'Beedrill-Mega' }],
  'Blastoise': [{ item: 'Blastoisinite', forme: 'Blastoise-Mega' }],
  'Blaziken': [{ item: 'Blazikenite', forme: 'Blaziken-Mega' }],
  'Camerupt': [{ item: 'Cameruptite', forme: 'Camerupt-Mega' }],
  'Charizard': [
    { item: 'Charizardite X', forme: 'Charizard-Mega-X' },
    { item: 'Charizardite Y', forme: 'Charizard-Mega-Y' }
  ],
  'Diancie': [{ item: 'Diancite', forme: 'Diancie-Mega' }],
  'Gallade': [{ item: 'Galladite', forme: 'Gallade-Mega' }],
  'Garchomp': [{ item: 'Garchompite', forme: 'Garchomp-Mega' }],
  'Gardevoir': [{ item: 'Gardevoirite', forme: 'Gardevoir-Mega' }],
  'Gengar': [{ item: 'Gengarite', forme: 'Gengar-Mega' }],
  'Glalie': [{ item: 'Glalitite', forme: 'Glalie-Mega' }],
  'Gyarados': [{ item: 'Gyaradosite', forme: 'Gyarados-Mega' }],
  'Heracross': [{ item: 'Heracronite', forme: 'Heracross-Mega' }],
  'Houndoom': [{ item: 'Houndoominite', forme: 'Houndoom-Mega' }],
  'Kangaskhan': [{ item: 'Kangaskhanite', forme: 'Kangaskhan-Mega' }],
  'Latias': [{ item: 'Latiasite', forme: 'Latias-Mega' }],
  'Latios': [{ item: 'Latiosite', forme: 'Latios-Mega' }],
  'Lopunny': [{ item: 'Lopunnite', forme: 'Lopunny-Mega' }],
  'Lucario': [{ item: 'Lucarionite', forme: 'Lucario-Mega' }],
  'Manectric': [{ item: 'Manectite', forme: 'Manectric-Mega' }],
  'Mawile': [{ item: 'Mawilite', forme: 'Mawile-Mega' }],
  'Medicham': [{ item: 'Medichamite', forme: 'Medicham-Mega' }],
  'Metagross': [{ item: 'Metagrossite', forme: 'Metagross-Mega' }],
  'Mewtwo': [
    { item: 'Mewtwonite X', forme: 'Mewtwo-Mega-X' },
    { item: 'Mewtwonite Y', forme: 'Mewtwo-Mega-Y' }
  ],
  'Pidgeot': [{ item: 'Pidgeotite', forme: 'Pidgeot-Mega' }],
  'Pinsir': [{ item: 'Pinsirite', forme: 'Pinsir-Mega' }],
  'Sableye': [{ item: 'Sablenite', forme: 'Sableye-Mega' }],
  'Salamence': [{ item: 'Salamencite', forme: 'Salamence-Mega' }],
  'Sceptile': [{ item: 'Sceptilite', forme: 'Sceptile-Mega' }],
  'Scizor': [{ item: 'Scizorite', forme: 'Scizor-Mega' }],
  'Sharpedo': [{ item: 'Sharpedonite', forme: 'Sharpedo-Mega' }],
  'Slowbro': [{ item: 'Slowbronite', forme: 'Slowbro-Mega' }],
  'Steelix': [{ item: 'Steelixite', forme: 'Steelix-Mega' }],
  'Swampert': [{ item: 'Swampertite', forme: 'Swampert-Mega' }],
  'Tyranitar': [{ item: 'Tyranitarite', forme: 'Tyranitar-Mega' }],
  'Venusaur': [{ item: 'Venusaurite', forme: 'Venusaur-Mega' }],
};